[tox]
requires =
    tox>=4.2
env_list =
    {py311, py310, py39, py38}-django{40}

[testenv]
deps =
    coverage
    django40: Django<4.1,>=4
set_env =
    DJANGO_SETTINGS_MODULE = testauth.settings.local
commands =
    coverage run runtests.py memberaudit_securegroups -v 2
    coverage xml
    coverage report
install_command = python -m pip install -U {opts} {packages}
