# Generated by Django 4.0.10 on 2023-10-09 22:23

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit", "0013_add_corporation_titles"),
        ("memberaudit_securegroups", "0003_add_corporation_role_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillsetfilter",
            name="character_type",
            field=models.CharField(
                blank=True,
                choices=[("AN", "any"), ("MO", "mains only"), ("AO", "alts only")],
                default="AN",
                help_text="Specify the type of character that needs to have the skill set.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="skillsetfilter",
            name="skill_sets",
            field=models.ManyToManyField(
                help_text="Users must have a character who possess all of the skills in <strong>one</strong> of the selected skill sets.",
                to="memberaudit.skillset",
            ),
        ),
    ]
