# Generated by Django 4.0.10 on 2023-10-08 19:24

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit_securegroups", "0004_corporationrolefilter_is_main_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="corporationrolefilter",
            old_name="is_main",
            new_name="mains_only",
        ),
    ]
