# Generated by Django 4.0.10 on 2024-02-08 19:05

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit_securegroups", "0004_corporationtitlefilter"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeInCorporationFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The filter description that is shown to end users.",
                        max_length=500,
                    ),
                ),
                (
                    "minimum_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minimum number of days a main character needs to be member of his/her current corporation.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
