# Generated by Django 4.0.10 on 2023-10-08 20:40

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "memberaudit_securegroups",
            "0005_rename_is_main_corporationrolefilter_mains_only",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corporationrolefilter",
            name="mains_only",
        ),
        migrations.AddField(
            model_name="corporationrolefilter",
            name="allow_alts",
            field=models.BooleanField(
                default=False,
                help_text="When True characters which are not mains are also considered.",
            ),
        ),
    ]
