# Generated by Django 4.0.10 on 2024-02-08 18:49

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit_securegroups", "0005_minimumcorporationmembership"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MinimumCorporationMembership",
            new_name="TimeInCorporationFilter",
        ),
    ]
