# Generated by Django 4.0.10 on 2023-10-08 20:42

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "memberaudit_securegroups",
            "0006_remove_corporationrolefilter_mains_only_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corporationrolefilter",
            name="allow_alts",
        ),
        migrations.AddField(
            model_name="corporationrolefilter",
            name="include_alts",
            field=models.BooleanField(
                default=False,
                help_text="When True the filter will also include characters which are not mains.",
            ),
        ),
    ]
