# Generated by Django 4.0.10 on 2024-02-08 18:53

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "memberaudit_securegroups",
            "0006_rename_minimumcorporationmembership_timeincorporationfilter",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeincorporationfilter",
            name="days",
        ),
        migrations.AddField(
            model_name="timeincorporationfilter",
            name="minimum_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Minimum number of days a main character needs to be member of his/her current corporation.",
            ),
        ),
    ]
